version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "19:00"
      timezone: "America/Los_Angeles"
    assignees:
      - "dchansen06"
      - "coderask"
    groups:
      actions-updates:
        patterns:
          - "*"
    commit-message:
      prefix: "Dependabot"
      include: "scope"
