name: Unit Tests
run-name: Unit Tests - ${{ github.ref_name }}

on:
  push:
    branches: [main]
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
  workflow_dispatch:

env:
  ARM_GCC_VERSION: "12.2.Rel1"

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  cmake:
    name: CMake Builds
    runs-on: ${{ matrix.operatingSystem }}
    permissions:
      contents: read
      actions: write
    strategy:
      fail-fast: true
      matrix:
        prefix: ["Debug", "Release", "MinSizeRel", "RelWithDebInfo"]
        operatingSystem: ${{ github.event_name == 'pull_request' && github.event.pull_request.draft && fromJson('["ubuntu-latest"]') || fromJson('["ubuntu-latest", "windows-latest", "macos-latest"]') }}
    env:
      SCCACHE_DIR: ${{ github.workspace }}/sccache
      SCCACHE_LOG: "info"
      SCCACHE_ERROR_LOG: ${{ github.workspace }}/sccache-error.log
      SCCACHE_SERVER_PORT: ${{ matrix.prefix == 'Debug' && '4226' || (matrix.prefix == 'Release' && '4227' || (matrix.prefix == 'MinSizeRel' && '4228' || '4229')) }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          fetch-depth: 1

      - name: Install Arm Toolchain
        uses: carlosperate/arm-none-eabi-gcc-action@0725d97b026acf7fc8e22dfd5bee912998879ba8 # v1.12.3
        with:
          release: ${{ env.ARM_GCC_VERSION }}

      - name: Setup Cache
        id: cache-setup
        continue-on-error: true
        uses: actions/cache@55cc8345863c7cc4c66a329aec7e433d2d1c52a9 # v6.1.0
        with:
          path: ${{ env.SCCACHE_DIR }}
          key: sccache-${{ runner.os }}-${{ env.ARM_GCC_VERSION }}-${{ github.job }}-${{ matrix.prefix }}-${{ github.ref_name }}
          restore-keys: |
            sccache-${{ runner.os }}-${{ env.ARM_GCC_VERSION }}-${{ github.job }}-${{ matrix.prefix }}-${{ github.ref_name }}
            sccache-${{ runner.os }}-${{ env.ARM_GCC_VERSION }}-${{ github.job }}-${{ matrix.prefix }}-main
            sccache-${{ runner.os }}-${{ env.ARM_GCC_VERSION }}-${{ github.job }}-${{ matrix.prefix }}-
            sccache-${{ runner.os }}-${{ env.ARM_GCC_VERSION }}-${{ github.job }}-

      - name: Setup Shared Compilation Cache
        id: sccache-setup
        if: steps.cache-setup.outcome == 'success'
        continue-on-error: true
        uses: mozilla-actions/sccache-action@9e7fa8a12102821edf02ca5dbea1acd0f89a2696 # v0.0.10

      - name: Start Shared Compilation Cache Server
        id: sccache-start
        continue-on-error: true
        if: steps.sccache-setup.outcome == 'success'
        run: sccache --start-server

      - name: CMake Configuration (Unix)
        if: matrix.operatingSystem != 'windows-latest'
        shell: bash
        run: |
          set -o pipefail
          echo "<details><summary>CMake Configuration</summary>" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "\`\`\`" >> $GITHUB_STEP_SUMMARY
          cmake --preset ${{ matrix.prefix }} 2>&1 | tee -a $GITHUB_STEP_SUMMARY
          echo "\`\`\`" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "</details>" >> $GITHUB_STEP_SUMMARY

      - name: CMake Configuration (Windows)
        if: matrix.operatingSystem == 'windows-latest'
        shell: pwsh
        run: |
          echo "<details><summary>CMake Configuration</summary>" | Out-File -FilePath $env:GITHUB_STEP_SUMMARY -Append
          echo "" | Out-File -FilePath $env:GITHUB_STEP_SUMMARY -Append
          echo "``````" | Out-File -FilePath $env:GITHUB_STEP_SUMMARY -Append
          cmake --preset ${{ matrix.prefix }} 2>&1 | Tee-Object -FilePath $env:GITHUB_STEP_SUMMARY -Append
          echo "``````" | Out-File -FilePath $env:GITHUB_STEP_SUMMARY -Append
          echo "" | Out-File -FilePath $env:GITHUB_STEP_SUMMARY -Append
          echo "</details>" | Out-File -FilePath $env:GITHUB_STEP_SUMMARY -Append

      - name: CMake Build (Unix)
        if: matrix.operatingSystem != 'windows-latest'
        shell: bash
        run: |
          set -o pipefail
          echo "<details><summary>CMake Build</summary>" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "\`\`\`" >> $GITHUB_STEP_SUMMARY
          cmake --build --preset ${{ matrix.prefix }} 2>&1 | tee -a $GITHUB_STEP_SUMMARY
          echo "\`\`\`" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "</details>" >> $GITHUB_STEP_SUMMARY

      - name: CMake Build (Windows)
        if: matrix.operatingSystem == 'windows-latest'
        shell: pwsh
        run: |
          echo "<details><summary>CMake Build</summary>" | Out-File -FilePath $env:GITHUB_STEP_SUMMARY -Append
          echo "" | Out-File -FilePath $env:GITHUB_STEP_SUMMARY -Append
          echo "``````" | Out-File -FilePath $env:GITHUB_STEP_SUMMARY -Append
          cmake --build --preset ${{ matrix.prefix }} 2>&1 | Tee-Object -FilePath $env:GITHUB_STEP_SUMMARY -Append
          echo "``````" | Out-File -FilePath $env:GITHUB_STEP_SUMMARY -Append
          echo "" | Out-File -FilePath $env:GITHUB_STEP_SUMMARY -Append
          echo "</details>" | Out-File -FilePath $env:GITHUB_STEP_SUMMARY -Append

      - name: Executable Size (Unix)
        if: matrix.operatingSystem != 'windows-latest'
        shell: bash
        run: |
          set -o pipefail
          echo "<details open><summary>Executable Size</summary>" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "\`\`\`" >> $GITHUB_STEP_SUMMARY
          arm-none-eabi-size build/${{ matrix.prefix }}/*.elf 2>&1 | tee -a $GITHUB_STEP_SUMMARY
          echo "\`\`\`" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "</details>" >> $GITHUB_STEP_SUMMARY

      - name: Executable Size (Windows)
        if: matrix.operatingSystem == 'windows-latest'
        shell: pwsh
        run: |
          echo "<details open><summary>Executable Size</summary>" | Out-File -FilePath $env:GITHUB_STEP_SUMMARY -Append
          echo "" | Out-File -FilePath $env:GITHUB_STEP_SUMMARY -Append
          echo "``````" | Out-File -FilePath $env:GITHUB_STEP_SUMMARY -Append
          $elfFiles = Get-ChildItem build\${{ matrix.prefix }}\*.elf | ForEach-Object { $_.FullName }
          arm-none-eabi-size $elfFiles | Tee-Object -FilePath $env:GITHUB_STEP_SUMMARY -Append
          echo "``````" | Out-File -FilePath $env:GITHUB_STEP_SUMMARY -Append
          echo "" | Out-File -FilePath $env:GITHUB_STEP_SUMMARY -Append
          echo "</details>" | Out-File -FilePath $env:GITHUB_STEP_SUMMARY -Append

      - name: Shared Compilation Cache Errors (Unix)
        if: matrix.operatingSystem != 'windows-latest' && steps.sccache-setup.outcome == 'success'
        shell: bash
        run: |
          set -o pipefail
          if [ -f "$SCCACHE_ERROR_LOG" ]; then
            echo "<details><summary>Shared Compilation Cache Errors</summary>" >> $GITHUB_STEP_SUMMARY
            echo "" >> $GITHUB_STEP_SUMMARY
            echo "\`\`\`" >> $GITHUB_STEP_SUMMARY
            cat "$SCCACHE_ERROR_LOG" | tee -a $GITHUB_STEP_SUMMARY
            echo "\`\`\`" >> $GITHUB_STEP_SUMMARY
            echo "" >> $GITHUB_STEP_SUMMARY
            echo "</details>" >> $GITHUB_STEP_SUMMARY
          fi

      - name: Shared Compilation Cache Errors (Windows)
        if: matrix.operatingSystem == 'windows-latest' && steps.sccache-setup.outcome == 'success'
        shell: pwsh
        run: |
          if (Test-Path $env:SCCACHE_ERROR_LOG) {
            echo "<details><summary>Shared Compilation Cache Errors</summary>" | Out-File -FilePath $env:GITHUB_STEP_SUMMARY -Append
            echo "" | Out-File -FilePath $env:GITHUB_STEP_SUMMARY -Append
            echo "``````" | Out-File -FilePath $env:GITHUB_STEP_SUMMARY -Append
            Get-Content $env:SCCACHE_ERROR_LOG | Tee-Object -FilePath $env:GITHUB_STEP_SUMMARY -Append
            echo "``````" | Out-File -FilePath $env:GITHUB_STEP_SUMMARY -Append
            echo "" | Out-File -FilePath $env:GITHUB_STEP_SUMMARY -Append
            echo "</details>" | Out-File -FilePath $env:GITHUB_STEP_SUMMARY -Append
          }

      - name: Upload Ubuntu RelWithDebInfo Builds
        if: matrix.prefix == 'RelWithDebInfo' && matrix.operatingSystem == 'ubuntu-latest'
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: firmware-release-with-debug-info
          path: build/${{ matrix.prefix }}/*.elf
          retention-days: 7
          if-no-files-found: error
          compression-level: 0
          overwrite: true

  ctest:
    name: CTest
    needs: cmake
    runs-on: ${{ matrix.operatingSystem }}
    permissions:
      contents: read
      actions: write
    strategy:
      fail-fast: true
      matrix:
        operatingSystem: ${{ github.event_name == 'pull_request' && github.event.pull_request.draft && fromJson('["ubuntu-latest"]') || fromJson('["ubuntu-latest", "windows-latest", "macos-latest"]') }}
    env:
      SCCACHE_DIR: ${{ github.workspace }}/sccache
      SCCACHE_LOG: "info"
      SCCACHE_ERROR_LOG: ${{ github.workspace }}/sccache-error.log
    steps:
      - name: Checkout Repository
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          fetch-depth: 1

      - name: Setup Cache
        id: cache-setup
        continue-on-error: true
        uses: actions/cache@55cc8345863c7cc4c66a329aec7e433d2d1c52a9 # v6.1.0
        with:
          path: ${{ env.SCCACHE_DIR }}
          key: sccache-${{ runner.os }}-${{ env.ARM_GCC_VERSION }}-${{ github.job }}-${{ github.ref_name }}
          restore-keys: |
            sccache-${{ runner.os }}-${{ env.ARM_GCC_VERSION }}-${{ github.job }}-${{ github.ref_name }}
            sccache-${{ runner.os }}-${{ env.ARM_GCC_VERSION }}-${{ github.job }}-main
            sccache-${{ runner.os }}-${{ env.ARM_GCC_VERSION }}-${{ github.job }}-

      - name: Setup Shared Compilation Cache
        id: sccache-setup
        if: steps.cache-setup.outcome == 'success'
        uses: mozilla-actions/sccache-action@9e7fa8a12102821edf02ca5dbea1acd0f89a2696 # v0.0.10
        continue-on-error: true

      - name: Start Shared Compilation Cache Server
        id: sccache-start
        continue-on-error: true
        if: steps.sccache-setup.outcome == 'success'
        run: sccache --start-server

      - name: CMake Configuration (Unix)
        if: matrix.operatingSystem != 'windows-latest'
        shell: bash
        run: |
          set -o pipefail
          echo "<details><summary>CMake Configuration (HOOTLTest)</summary>" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "\`\`\`" >> $GITHUB_STEP_SUMMARY
          cmake --preset HOOTLTest 2>&1 | tee -a $GITHUB_STEP_SUMMARY
          echo "\`\`\`" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "</details>" >> $GITHUB_STEP_SUMMARY

      - name: CMake Configuration (Windows)
        if: matrix.operatingSystem == 'windows-latest'
        shell: pwsh
        run: |
          echo "<details><summary>CMake Configuration (HOOTLTest)</summary>" | Out-File -FilePath $env:GITHUB_STEP_SUMMARY -Append
          echo "" | Out-File -FilePath $env:GITHUB_STEP_SUMMARY -Append
          echo "``````" | Out-File -FilePath $env:GITHUB_STEP_SUMMARY -Append
          cmake --preset HOOTLTest 2>&1 | Tee-Object -FilePath $env:GITHUB_STEP_SUMMARY -Append
          echo "``````" | Out-File -FilePath $env:GITHUB_STEP_SUMMARY -Append
          echo "" | Out-File -FilePath $env:GITHUB_STEP_SUMMARY -Append
          echo "</details>" | Out-File -FilePath $env:GITHUB_STEP_SUMMARY -Append

      - name: CMake Build (Unix)
        if: matrix.operatingSystem != 'windows-latest'
        shell: bash
        run: |
          set -o pipefail
          echo "<details><summary>CMake Build (HOOTLTest)</summary>" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "\`\`\`" >> $GITHUB_STEP_SUMMARY
          cmake --build --preset HOOTLTest 2>&1 | tee -a $GITHUB_STEP_SUMMARY
          echo "\`\`\`" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "</details>" >> $GITHUB_STEP_SUMMARY

      - name: CMake Build (Windows)
        if: matrix.operatingSystem == 'windows-latest'
        shell: pwsh
        run: |
          echo "<details><summary>CMake Build (HOOTLTest)</summary>" | Out-File -FilePath $env:GITHUB_STEP_SUMMARY -Append
          echo "" | Out-File -FilePath $env:GITHUB_STEP_SUMMARY -Append
          echo "``````" | Out-File -FilePath $env:GITHUB_STEP_SUMMARY -Append
          cmake --build --preset HOOTLTest 2>&1 | Tee-Object -FilePath $env:GITHUB_STEP_SUMMARY -Append
          echo "``````" | Out-File -FilePath $env:GITHUB_STEP_SUMMARY -Append
          echo "" | Out-File -FilePath $env:GITHUB_STEP_SUMMARY -Append
          echo "</details>" | Out-File -FilePath $env:GITHUB_STEP_SUMMARY -Append

      - name: Run CTest (Unix)
        if: matrix.operatingSystem != 'windows-latest'
        shell: bash
        run: |
          set -o pipefail
          echo "<details open><summary>Run CTest (HOOTLTest)</summary>" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "\`\`\`" >> $GITHUB_STEP_SUMMARY
          ctest --output-on-failure --test-dir build/HOOTLTest 2>&1 | tee -a $GITHUB_STEP_SUMMARY
          echo "\`\`\`" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "</details>" >> $GITHUB_STEP_SUMMARY

      - name: Run CTest (Windows)
        if: matrix.operatingSystem == 'windows-latest'
        shell: pwsh
        run: |
          echo "<details open><summary>Run CTest (HOOTLTest)</summary>" | Out-File -FilePath $env:GITHUB_STEP_SUMMARY -Append
          echo "" | Out-File -FilePath $env:GITHUB_STEP_SUMMARY -Append
          echo "``````" | Out-File -FilePath $env:GITHUB_STEP_SUMMARY -Append
          ctest --output-on-failure --test-dir build/HOOTLTest 2>&1 | Tee-Object -FilePath $env:GITHUB_STEP_SUMMARY -Append
          echo "``````" | Out-File -FilePath $env:GITHUB_STEP_SUMMARY -Append
          echo "" | Out-File -FilePath $env:GITHUB_STEP_SUMMARY -Append
          echo "</details>" | Out-File -FilePath $env:GITHUB_STEP_SUMMARY -Append

      - name: Shared Compilation Cache Errors (Unix)
        if: matrix.operatingSystem != 'windows-latest' && steps.sccache-setup.outcome == 'success'
        continue-on-error: true
        shell: bash
        run: |
          set -o pipefail
          if [ -f "$SCCACHE_ERROR_LOG" ]; then
            echo "<details><summary>Shared Compilation Cache Errors</summary>" >> $GITHUB_STEP_SUMMARY
            echo "" >> $GITHUB_STEP_SUMMARY
            echo "\`\`\`" >> $GITHUB_STEP_SUMMARY
            cat "$SCCACHE_ERROR_LOG" | tee -a $GITHUB_STEP_SUMMARY
            echo "\`\`\`" >> $GITHUB_STEP_SUMMARY
            echo "" >> $GITHUB_STEP_SUMMARY
            echo "</details>" >> $GITHUB_STEP_SUMMARY
          fi

      - name: Shared Compilation Cache Errors (Windows)
        if: matrix.operatingSystem == 'windows-latest' && steps.sccache-setup.outcome == 'success'
        continue-on-error: true
        shell: pwsh
        run: |
          if (Test-Path $env:SCCACHE_ERROR_LOG) {
            echo "<details><summary>Shared Compilation Cache Errors</summary>" | Out-File -FilePath $env:GITHUB_STEP_SUMMARY -Append
            echo "" | Out-File -FilePath $env:GITHUB_STEP_SUMMARY -Append
            echo "``````" | Out-File -FilePath $env:GITHUB_STEP_SUMMARY -Append
            Get-Content $env:SCCACHE_ERROR_LOG | Tee-Object -FilePath $env:GITHUB_STEP_SUMMARY -Append
            echo "``````" | Out-File -FilePath $env:GITHUB_STEP_SUMMARY -Append
            echo "" | Out-File -FilePath $env:GITHUB_STEP_SUMMARY -Append
            echo "</details>" | Out-File -FilePath $env:GITHUB_STEP_SUMMARY -Append
          }

  valgrind:
    name: Valgrind
    needs: cmake
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout Repository
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          fetch-depth: 1

      - name: Set up Valgrind
        uses: awalsh128/cache-apt-pkgs-action@553a35bb8ebd9fcabcb1c9451aa4c98e1b4ca8a9 # v1.6.3
        with:
          packages: valgrind

      - name: Build and Run Memory Check
        run: |
          set -o pipefail
          echo "<details open><summary>HOOTLTest Memory Check</summary>" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "\`\`\`" >> $GITHUB_STEP_SUMMARY
          make valgrind 2>&1 | tee -a $GITHUB_STEP_SUMMARY
          echo "\`\`\`" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "</details>" >> $GITHUB_STEP_SUMMARY

  prove:
    if: false # TODO Implement formal testing for CANfigurator
    name: Prove CANfigurator
    runs-on: ubuntu-slim
    permissions: {}
    steps:
      - name: Placeholder for CANfigurator Unit Tests
        run: echo "Placeholder for CANfigurator unit tests using Prove (or some other testing framework)."

  all:
    if: ${{ !github.event.pull_request.draft && always() }}
    name: Completed All HOOTL Unit Tests
    needs: [cmake, ctest, valgrind] # TODO Add prove once implemented
    runs-on: ubuntu-slim
    permissions: {}
    steps:
      - name: Fail HOOTL Unit Tests
        if: > # TODO Add prove once implemented
          ${{
            needs.cmake.result != 'success' ||
            needs.ctest.result != 'success' ||
            needs.valgrind.result != 'success'
          }}
        run: |
          echo "One or more HOOTL unit test jobs have failed."
          echo "Please review the logs of the individual jobs for more details."
          exit 1

      - name: Complete HOOTL Unit Tests
        run: |
          echo "All HOOTL unit tests have been executed across all operating systems."
          echo "Please refer to the individual job logs for detailed information on each test run."
